import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ClerkProvider, SignedIn, SignedOut, UserButton, SignInButton } from "@clerk/nextjs";
import { SyncUser } from "../components/SyncUser";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ClerkProvider>
          <div className="px-4 py-2 border-b flex justify-end gap-3">
            <SignedOut>
              <SignInButton>
                <button className="text-sm px-3 py-1 rounded border">Sign in</button>
              </SignInButton>
            </SignedOut>
            <SignedIn>
              {/* Persist Clerk user to API/DB */}
              <SyncUser />
              <UserButton afterSignOutUrl="/" />
            </SignedIn>
          </div>
          {children}
        </ClerkProvider>
      </body>
    </html>
  );
}
